
//----------------------------------------------------
// The following code was generated by CUP v0.10k
// Wed Apr 11 11:47:12 CDT 2018
//----------------------------------------------------

package com.own.develop.compiler;

/** CUP generated class containing symbol constants. */
public class sym {
  /* terminals */
  public static final int PROCEDURE = 2;
  public static final int INPUT = 19;
  public static final int IS = 3;
  public static final int ELSE = 17;
  public static final int ENDLOOP = 14;
  public static final int ENDIF = 18;
  public static final int EQUAL = 9;
  public static final int THEN = 16;
  public static final int SEMI = 6;
  public static final int IN = 11;
  public static final int PIZQ = 21;
  public static final int LOOP = 13;
  public static final int IDENTIFIER = 29;
  public static final int PDER = 22;
  public static final int END = 8;
  public static final int IF = 15;
  public static final int BEGIN = 7;
  public static final int OP_SUB = 25;
  public static final int EOF = 0;
  public static final int DIGITO = 28;
  public static final int OP_DIV = 27;
  public static final int OP_ADD = 24;
  public static final int error = 1;
  public static final int OP_MULT = 26;
  public static final int INTEGER = 4;
  public static final int TWOP = 5;
  public static final int FOR = 10;
  public static final int NULL = 23;
  public static final int OUTPUT = 20;
  public static final int TO = 12;
}

